name: simple-echo-loop
on:
  workflow_dispatch:

jobs:
  job:
    name: setup target modules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: loop
        run: |
          for file in `ls commands`; do
            echo "${file}"
          done
